include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print: false
    - use_key_in_widget_constructors: false

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
